# Generated by Django 5.0.6 on 2026-07-26 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('movement_type', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('production_consumption', 'Production Consumption'), ('production_output', 'Production Output'), ('sales_shipment', 'Sales Shipment'), ('transfer_in', 'Warehouse Transfer In'), ('transfer_out', 'Warehouse Transfer Out'), ('adjustment', 'Manual Adjustment'), ('damage', 'Damaged / Written Off')], max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_damaged', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_items', to='products.product')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
