# Generated by Django 6.0.6 on 2026-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacecategory_bg_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepartner',
            name='approval_time_days',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='audit_time_days',
            field=models.PositiveSmallIntegerField(blank=True, default=14, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='average_delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='certificates_issued',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='consulting_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='eco_friendly_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='express_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='has_cold_chain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='label_printing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='last_mile_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='packaging_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='packaging_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='pallet_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='primary_industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='private_label_support',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='production_lines_count',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='rack_system',
            field=models.CharField(blank=True, default='Multi-Tier Automated Pallet Racking', max_length=150),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='sub_industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='warehouse_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='wms_supported',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
