# Generated by Django 6.0.6 on 2026-08-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplacepartner_approval_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepartner',
            name='annual_capacity',
            field=models.CharField(blank=True, default='1.2M units/yr', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='cities_served',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='countries_served',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='current_utilization_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=75, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='custom_manufacturing_support',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='daily_capacity',
            field=models.CharField(blank=True, default='5,000 units/day', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='export_markets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='export_ready',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='head_office',
            field=models.CharField(blank=True, default='Ahmedabad, Gujarat', max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='installation_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='inventory_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='maintenance_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='maximum_capacity',
            field=models.CharField(blank=True, default='200,000 units/mo', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='quality_inspection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='revenue_range',
            field=models.CharField(blank=True, default='$5M - $25M', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='secondary_industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='specialization',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='target_market',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='technical_documentation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='training_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepartner',
            name='white_label_support',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
