# Generated by Django 6.0.7 on 2026-08-02 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('module', models.CharField(choices=[('marketplace', 'Marketplace AI v1'), ('procurement', 'Procurement AI'), ('inventory', 'Inventory AI'), ('production', 'Production AI'), ('general', 'General Copilot')], default='marketplace', max_length=50)),
                ('question', models.TextField(help_text='User input question or query')),
                ('response_text', models.TextField(help_text='Final text response returned by AI Assistant')),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='List of tool names and parameters invoked during reasoning')),
                ('records_count', models.PositiveSmallIntegerField(default=0, help_text='Number of database records passed to LLM context')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Total elapsed execution time in milliseconds')),
                ('model_version', models.CharField(blank=True, default='gemini-2.5-flash', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interaction Log',
                'verbose_name_plural': 'AI Interaction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
