# Generated by Django 6.0.7 on 2026-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteractionlog',
            name='module',
            field=models.CharField(choices=[('marketplace', 'Marketplace AI v1'), ('procurement', 'Procurement AI'), ('inventory', 'Inventory AI'), ('production', 'Production AI'), ('general', 'General Copilot'), ('copilot', 'Enterprise AI Copilot V2'), ('product_builder', 'AI Product Builder'), ('product_validator', 'AI Product Validator'), ('procurement_planner', 'AI Procurement Planner'), ('document_generator', 'AI Document Generator')], default='marketplace', max_length=50),
        ),
    ]
