export const ALL_PROJECTS = [
    {
        id: "PP-001", emoji: "💪", name: "Protein Powder", category: "Nutrition",
        stage: "Planning", stageColor: "#3b82f6", stageBg: "rgba(59,130,246,0.1)",
        progress: 34, health: 92, healthColor: "#16a34a",
        budget: 5000000, spent: 1600000, profit: 8500000,
        launch: "Jan 15, 2025", risk: "low", riskLabel: "Low Risk",
        suppliers: 3, manufacturer: "Nutraceutix Labs", warehouse: "Mumbai Hub",
        transport: "BlueDart Express", milestone: "Supplier Shortlist",
        aiInsight: "Switch to BioSynth India — save ₹2.4L on manufacturing costs.",
        priority: "high", model: "Third Party",
    },
    {
        id: "CB-002", emoji: "☕", name: "Coffee Brand", category: "Beverages",
        stage: "Manufacturing", stageColor: "#f97316", stageBg: "rgba(249,115,22,0.1)",
        progress: 74, health: 84, healthColor: "#16a34a",
        budget: 12000000, spent: 8160000, profit: 22000000,
        launch: "Nov 2, 2024", risk: "medium", riskLabel: "Minor Delay",
        suppliers: 5, manufacturer: "Global Roasters Co", warehouse: "Delhi NCR Hub",
        transport: "VRL Logistics", milestone: "Quality Audit",
        aiInsight: "Consolidate PO-8919 & PO-8921 for ₹45K freight savings.",
        priority: "high", model: "Contract",
    },
    {
        id: "SS-003", emoji: "🧴", name: "Skin Serum", category: "Cosmetics",
        stage: "Supplier Selection", stageColor: "#a855f7", stageBg: "rgba(168,85,247,0.1)",
        progress: 12, health: 78, healthColor: "#eab308",
        budget: 3000000, spent: 240000, profit: 6200000,
        launch: "Q2 2025", risk: "low", riskLabel: "On Track",
        suppliers: 2, manufacturer: "Not Assigned", warehouse: "Bangalore Hub",
        transport: "Not Assigned", milestone: "Supplier Finalization",
        aiInsight: "PharmaForm Co. is 94% match for your spec — recommend shortlisting.",
        priority: "medium", model: "Private Label",
    },
    {
        id: "EH-004", emoji: "🎧", name: "Earbuds Pro", category: "Electronics",
        stage: "Packaging", stageColor: "#14b8a6", stageBg: "rgba(20,184,166,0.1)",
        progress: 82, health: 89, healthColor: "#16a34a",
        budget: 8500000, spent: 6970000, profit: 15000000,
        launch: "Oct 30, 2024", risk: "low", riskLabel: "On Track",
        suppliers: 7, manufacturer: "TechMake Industries", warehouse: "Pune Facility",
        transport: "Delhivery", milestone: "Packaging Approval",
        aiInsight: "Launch window is optimal. Pre-order campaign recommended for Diwali.",
        priority: "high", model: "Own",
    },
    {
        id: "WC-005", emoji: "🪑", name: "Wooden Chair", category: "Furniture",
        stage: "Logistics", stageColor: "#16a34a", stageBg: "rgba(22,163,74,0.1)",
        progress: 91, health: 96, healthColor: "#16a34a",
        budget: 2200000, spent: 2002000, profit: 4800000,
        launch: "Oct 20, 2024", risk: "low", riskLabel: "On Track",
        suppliers: 4, manufacturer: "CraftWood India", warehouse: "Chennai Hub",
        transport: "TCI Express", milestone: "Final Dispatch",
        aiInsight: "Shipment on schedule. Arrange showroom display slots in advance.",
        priority: "medium", model: "Own",
    },
    {
        id: "VP-006", emoji: "💊", name: "Vitamin Pack", category: "Pharmaceutical",
        stage: "Delayed", stageColor: "#ba1a1a", stageBg: "rgba(186,26,26,0.1)",
        progress: 45, health: 52, healthColor: "#ba1a1a",
        budget: 4500000, spent: 2025000, profit: 9500000,
        launch: "Dec 1, 2024", risk: "high", riskLabel: "High Risk",
        suppliers: 3, manufacturer: "MediForm Labs", warehouse: "Hyderabad Hub",
        transport: "Not Assigned", milestone: "Regulatory Clearance",
        aiInsight: "FSSAI clearance delayed. Escalate to expedited review track immediately.",
        priority: "high", model: "Third Party",
    },
];

export const STAGE_COLORS = {
    "Planning": { color: "#3b82f6", label: "Planning" },
    "Supplier Selection": { color: "#a855f7", label: "Supplier Selection" },
    "Manufacturing": { color: "#f97316", label: "Manufacturing" },
    "Packaging": { color: "#14b8a6", label: "Packaging" },
    "Logistics": { color: "#16a34a", label: "Logistics" },
    "Completed": { color: "#6b7280", label: "Completed" },
    "Delayed": { color: "#ba1a1a", label: "Delayed" },
};
