# Generated by Django 6.0.7 on 2026-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_insights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_partners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='commercial_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_method',
            field=models.CharField(blank=True, default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='documents_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='logistics_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_recommendations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.CharField(blank=True, default='medium', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='Finished Product', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_materials_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='target_industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='target_market',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='team_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='stage',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Idea', 'Idea'), ('Supplier', 'Supplier Selection'), ('Manufacturer', 'Manufacturing'), ('Packaging', 'Packaging'), ('Production', 'Production'), ('QA', 'Quality Assurance'), ('Warehouse', 'Warehouse'), ('Transport', 'Transport & Logistics'), ('Completed', 'Completed'), ('delayed', 'Delayed'), ('planning', 'Planning'), ('supplier_selection', 'Supplier Selection'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics'), ('completed', 'Completed')], default='Planning', max_length=30),
        ),
    ]
