# Generated by Django 6.0.6 on 2026-08-03 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_members'),
        ('products', '0003_workspacecertificationagency_workspaceconsultant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WORKSPACE_CREATED', 'Workspace Created'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('conversation_history', models.JSONField(blank=True, default=list, help_text='[{"role": "ai"|"user", "content": "...", "timestamp": "..."}]')),
                ('collected_specs', models.JSONField(blank=True, default=dict, help_text='Structured specs extracted from conversation: product_name, category, budget, etc.')),
                ('ai_reasoning', models.JSONField(blank=True, default=list, help_text='AI reasoning trace for each decision: [{step, reasoning, confidence}]')),
                ('marketplace_results', models.JSONField(blank=True, default=dict, help_text='Cached marketplace search results for recommendations.')),
                ('current_phase', models.CharField(default='greeting', help_text='Current interview phase: greeting, product_basics, specifications, requirements, marketplace_search, review, complete', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.OneToOneField(blank=True, help_text='Linked after the AI creates the workspace from collected specs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_session', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
