# Generated by Django 6.0.7 on 2026-07-27 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='organizations.Membership', through_fields=('organization', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
